version: '3.7'

services:
  backend:
    restart: always
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    command: bash -c "python manage.py migrate & python manage.py runserver 0.0.0.0:5005"
    ports:
      - "5005:5005"
    env_file:
      - ./.env