# Generated by Django 5.1.3 on 2024-11-22 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0003_alter_task_column'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='column',
            name='task',
        ),
        migrations.AddField(
            model_name='column',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='columns', to='kanban.task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='column',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks_in_column', to='kanban.column'),
        ),
    ]
