# Generated by Django 5.1.3 on 2024-11-22 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0007_alter_task_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='creator',
        ),
    ]
